# Comprehensive Pre-commit Hooks Configuration
# Context-aware testing for Python, HTML/CSS, JavaScript with LLM fallback

repos:
  # Python Quality Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^(core|adapters|shared|scripts)/.*\.py$
      - id: end-of-file-fixer  
        files: ^(core|adapters|shared|scripts)/.*\.py$
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
        files: ^(core|adapters|shared|scripts)/.*\.py$

  # Python Static Type Checking with MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^(core|adapters|shared)/.*\.py$
        args: [--strict, --ignore-missing-imports, --show-error-codes]
        additional_dependencies: [types-requests, types-PyYAML]

  # Python Code Quality with Pylint (10/10 requirement)
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        files: ^(core|adapters|shared)/.*\.py$
        args: [--fail-under=10.0, --rcfile=.pylintrc]

  # Python Testing with pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        files: ^(core|adapters|shared)/.*\.py$
        args: [-v, --tb=short]
        pass_filenames: false

  # Architecture Validation (Custom Hook)
  - repo: local
    hooks:
      - id: architecture-validator
        name: Architecture Compliance Check
        entry: python shared/utils/architecture_validator.py
        language: system
        files: ^(core|adapters|shared)/.*\.py$
        pass_filenames: false

  # HTML Quality Hooks
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.11.0
    hooks:
      - id: stylelint
        files: \.(css|scss|sass)$
        args: [--fix]

  # HTML Validation
  - repo: local
    hooks:
      - id: html-validator
        name: HTML Validation
        entry: python -c "import html.parser; import sys; [html.parser.HTMLParser().feed(open(f).read()) for f in sys.argv[1:]]"
        language: system
        files: \.html?$

  # JavaScript Quality Hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.16.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        args: [--fix]

  # JavaScript Formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md)$

  # 3-Test Cycle with LLM Fallback (Custom Hook)
  - repo: local
    hooks:
      - id: smart-test-cycle
        name: 3-Test Cycle with LLM Fallback
        entry: python scripts/smart_test_cycle.py
        language: system
        files: ^(core|adapters|shared)/.*\.py$
        stages: [pre-push]
        pass_filenames: false

# Global Configuration
default_language_version:
  python: python3.12
  node: "18.17.0"

# Performance Optimization
default_stages: [pre-commit]
minimum_pre_commit_version: 2.20.0